@Api_HostAddress = http://localhost:5064
@LookupCode = TRANSACTION_CATEGORY

GET {{Api_HostAddress}}/api/Lookups/getByCode/{{LookupCode}}
Accept: application/json

###

@LookupId = 68621b20b112cf7303639046

GET {{Api_HostAddress}}/api/Lookups/getByCode/{{LookupId}}
Accept: application/json
